const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');

class ContractGenerator {
  constructor(outputDir = './contracts') {
    this.outputDir = outputDir;
    
    // Create contracts directory if it doesn't exist
    if (!fs.existsSync(this.outputDir)) {
      fs.mkdirSync(this.outputDir, { recursive: true });
    }
  }

  async generateSubcontractorAgreement(booking, gcInfo, subInfo) {
    return new Promise((resolve, reject) => {
      const filename = `contract_${booking.id}.pdf`;
      const filepath = path.join(this.outputDir, filename);
      
      const doc = new PDFDocument({ margin: 50 });
      const stream = fs.createWriteStream(filepath);
      
      doc.pipe(stream);

      // Header
      doc.fontSize(20).text('SUBCONTRACTOR AGREEMENT', { align: 'center' });
      doc.moveDown();
      doc.fontSize(10).text(`Agreement ID: ${booking.id}`, { align: 'center' });
      doc.text(`Date: ${new Date().toLocaleDateString()}`, { align: 'center' });
      doc.moveDown(2);

      // Parties
      doc.fontSize(14).text('PARTIES', { underline: true });
      doc.moveDown(0.5);
      doc.fontSize(10);
      
      doc.text(`General Contractor ("GC"):`, { continued: false });
      doc.fontSize(9);
      doc.text(`  Name: ${gcInfo.name}`);
      doc.text(`  ID: ${gcInfo.id}`);
      if (gcInfo.license) doc.text(`  License: ${gcInfo.license}`);
      doc.moveDown();

      doc.fontSize(10);
      doc.text(`Subcontractor ("Subcontractor"):`, { continued: false });
      doc.fontSize(9);
      doc.text(`  Name: ${subInfo.name}`);
      doc.text(`  ID: ${subInfo.id}`);
      if (subInfo.license) doc.text(`  License: ${subInfo.license}`);
      doc.moveDown(2);

      // Scope of Work
      doc.fontSize(14).text('SCOPE OF WORK', { underline: true });
      doc.moveDown(0.5);
      doc.fontSize(10);
      doc.text(`Trade: ${booking.trade.toUpperCase()}`);
      doc.text(`Location: ${booking.location}`);
      doc.moveDown(0.5);
      doc.fontSize(9);
      doc.text('Description:', { continued: false });
      doc.text(booking.scope || 'As discussed and agreed upon by both parties.');
      doc.moveDown(2);

      // Schedule
      doc.fontSize(14).text('SCHEDULE', { underline: true });
      doc.moveDown(0.5);
      doc.fontSize(10);
      doc.text(`Start Date: ${new Date(booking.startDate).toLocaleDateString()}`);
      doc.text(`End Date: ${new Date(booking.endDate).toLocaleDateString()}`);
      doc.moveDown(2);

      // Compensation
      doc.fontSize(14).text('COMPENSATION', { underline: true });
      doc.moveDown(0.5);
      doc.fontSize(10);
      doc.text(`Hourly Rate: $${booking.rate.toFixed(2)}/hour`);
      
      const estimatedHours = this.calculateEstimatedHours(booking.startDate, booking.endDate);
      const estimatedTotal = estimatedHours * booking.rate;
      doc.text(`Estimated Hours: ${estimatedHours}`);
      doc.text(`Estimated Total: $${estimatedTotal.toFixed(2)}`);
      doc.moveDown(0.5);
      doc.fontSize(9);
      doc.text('Payment terms: Net 30 days from invoice date, unless otherwise agreed.');
      doc.moveDown(2);

      // Terms and Conditions
      doc.fontSize(14).text('TERMS AND CONDITIONS', { underline: true });
      doc.moveDown(0.5);
      doc.fontSize(9);
      
      const terms = [
        'The Subcontractor agrees to perform the work in a professional and workmanlike manner.',
        'The Subcontractor shall provide all necessary tools, equipment, and materials unless otherwise specified.',
        'The Subcontractor shall maintain all required licenses, permits, and insurance coverage.',
        'The Subcontractor agrees to comply with all applicable laws, codes, and regulations.',
        'Either party may terminate this agreement with 48 hours written notice.',
        'This agreement is governed by the laws of the jurisdiction where the work is performed.',
        'This agreement was negotiated and confirmed via the ClawShake protocol.',
      ];

      terms.forEach((term, index) => {
        doc.text(`${index + 1}. ${term}`, { indent: 20 });
        doc.moveDown(0.3);
      });

      doc.moveDown(2);

      // Signatures
      doc.fontSize(14).text('SIGNATURES', { underline: true });
      doc.moveDown(1);
      
      doc.fontSize(9);
      doc.text('By accepting this agreement via ClawShake, both parties acknowledge and agree to the terms above.');
      doc.moveDown(1);

      doc.text(`GC Digital Signature: ACCEPTED via ClawShake on ${new Date().toLocaleDateString()}`);
      doc.moveDown(0.5);
      doc.text(`Subcontractor Digital Signature: ACCEPTED via ClawShake on ${new Date().toLocaleDateString()}`);
      doc.moveDown(2);

      // Footer
      doc.fontSize(8).text('Generated by ClawShake - Autonomous Contractor Negotiation Protocol', {
        align: 'center',
      });
      doc.text(`ClawShake Booking ID: ${booking.id}`, { align: 'center' });

      doc.end();

      stream.on('finish', () => {
        resolve(filepath);
      });

      stream.on('error', (err) => {
        reject(err);
      });
    });
  }

  calculateEstimatedHours(startDate, endDate) {
    const start = new Date(startDate);
    const end = new Date(endDate);
    const days = Math.ceil((end - start) / (1000 * 60 * 60 * 24)) + 1;
    return days * 8; // Assume 8-hour workdays
  }

  async generateInvoiceTemplate(booking, hours, gcInfo, subInfo) {
    return new Promise((resolve, reject) => {
      const filename = `invoice_${booking.id}_${Date.now()}.pdf`;
      const filepath = path.join(this.outputDir, filename);
      
      const doc = new PDFDocument({ margin: 50 });
      const stream = fs.createWriteStream(filepath);
      
      doc.pipe(stream);

      // Header
      doc.fontSize(24).text('INVOICE', { align: 'center' });
      doc.moveDown(2);

      // From/To
      doc.fontSize(12).text('FROM:', { underline: true });
      doc.fontSize(10);
      doc.text(subInfo.name);
      if (subInfo.address) doc.text(subInfo.address);
      if (subInfo.phone) doc.text(subInfo.phone);
      doc.moveDown();

      doc.fontSize(12).text('TO:', { underline: true });
      doc.fontSize(10);
      doc.text(gcInfo.name);
      if (gcInfo.address) doc.text(gcInfo.address);
      doc.moveDown(2);

      // Invoice details
      doc.fontSize(10);
      doc.text(`Invoice Date: ${new Date().toLocaleDateString()}`);
      doc.text(`Job Location: ${booking.location}`);
      doc.text(`Booking ID: ${booking.id}`);
      doc.moveDown(2);

      // Line items
      doc.fontSize(12).text('WORK PERFORMED', { underline: true });
      doc.moveDown(0.5);
      
      const rate = booking.rate;
      const total = hours * rate;

      doc.fontSize(10);
      doc.text(`${booking.trade} - ${booking.scope}`);
      doc.text(`Hours: ${hours} @ $${rate.toFixed(2)}/hr`);
      doc.moveDown();
      
      doc.fontSize(14);
      doc.text(`TOTAL DUE: $${total.toFixed(2)}`, { underline: true });
      doc.moveDown(2);

      doc.fontSize(9);
      doc.text('Payment due within 30 days.');
      doc.text('Thank you for your business!');

      doc.end();

      stream.on('finish', () => {
        resolve(filepath);
      });

      stream.on('error', (err) => {
        reject(err);
      });
    });
  }
}

module.exports = ContractGenerator;
